/**
 * i18n helpers. The locale set comes from profile (sourceLang + targetLangs);
 * nothing here assumes any specific language (golden rule #5).
 */
import type { LocalizedText } from "../../../engine/schemas/index.js";

/** Resolve localized text for a locale, falling back to the source language. */
export function t(
  text: LocalizedText | undefined,
  locale: string,
  sourceLang: string
): string {
  if (!text) return "";
  return text[locale]?.trim() ? text[locale]! : (text[sourceLang] ?? "");
}

/** Path prefix for a locale ("" for the default locale, "/en" otherwise). */
export function localePrefix(locale: string, defaultLocale: string): string {
  return locale === defaultLocale ? "" : `/${locale}`;
}

export function localePath(
  path: string,
  locale: string,
  defaultLocale: string
): string {
  const clean = path.startsWith("/") ? path : `/${path}`;
  return `${localePrefix(locale, defaultLocale)}${clean}` || "/";
}

/**
 * UI chrome strings (nav labels, section headings, meta labels). Content
 * comes from data; only interface furniture lives here. Locales without an
 * entry fall back to "en" strings.
 */
const UI: Record<string, Record<string, string>> = {
  ja: {
    "nav.projects": "Projects",
    "nav.history": "開発遍歴",
    "nav.about": "About",
    "nav.overview": "Overview",
    "home.featured": "Featured Projects",
    "home.skills": "技術スタック",
    "home.viewAll": "すべてのプロジェクト",
    "projects.title": "Projects",
    "projects.products": "Products & Services",
    "projects.lab": "Lab — OSS・実験",
    "projects.archive": "Archive",
    "project.problem": "課題",
    "project.motivation": "動機",
    "project.solution": "アプローチ",
    "project.results": "成果",
    "project.outcomes": "エンジニアリング成果",
    "project.highlights": "ハイライト",
    "project.timeline": "開発の転機",
    "project.stack": "技術スタック",
    "project.metrics": "開発メトリクス",
    "project.links": "リンク",
    "project.screenshots": "スクリーンショット",
    "project.architecture": "アーキテクチャ",
    "project.proprietary": "プロプライエタリ — アーキテクチャは記述、ソースは非公開",
    "project.evidence": "根拠",
    "project.role.solo": "ソロ開発",
    "project.role.lead": "リード",
    "project.role.contributor": "コントリビューター",
    "metrics.commits": "コミット",
    "metrics.activeDays": "活動日数",
    "metrics.span": "開発期間",
    "metrics.languages": "言語構成",
    "metrics.activity": "コミット活動",
    "metrics.velocity": "コミット/活動日",
    "metrics.byOwner": "本人コミット",
    "metrics.days": "日",
    "metrics.prs": "PR",
    "metrics.conventional": "規約準拠コミット",
    "viz.less": "少",
    "viz.more": "多",
    "viz.weeks": "週",
    "category.product": "製品",
    "category.service": "サービス",
    "category.client": "クライアント",
    "category.oss": "OSS",
    "category.hobby": "趣味",
    "category.learning": "学習",
    "evidence.owner": "owner",
    "history.title": "開発遍歴",
    "history.empty": "プロジェクトが増えると、ここに横断的な年表が育ちます。",
    "about.title": "About",
    "about.skills": "技術(全プロジェクトから算出・根拠リンク付き)",
    "overview.title": "Overview",
    "overview.note": "1枚で読める要約版です。",
    "seo.defaultTitle": "開発者ポートフォリオ",
    "footer.builtWith": "Generated by Provenfolio",
    "theme.switcher": "デザイン",
  },
  en: {
    "nav.projects": "Projects",
    "nav.history": "History",
    "nav.about": "About",
    "nav.overview": "Overview",
    "home.featured": "Featured Projects",
    "home.skills": "Tech Stack",
    "home.viewAll": "All projects",
    "projects.title": "Projects",
    "projects.products": "Products & Services",
    "projects.lab": "Lab — OSS & Experiments",
    "projects.archive": "Archive",
    "project.problem": "Problem",
    "project.motivation": "Motivation",
    "project.solution": "Approach",
    "project.results": "Results",
    "project.outcomes": "Engineering Outcomes",
    "project.highlights": "Highlights",
    "project.timeline": "Turning Points",
    "project.stack": "Tech Stack",
    "project.metrics": "Development Metrics",
    "project.links": "Links",
    "project.screenshots": "Screenshots",
    "project.architecture": "Architecture",
    "project.proprietary": "Proprietary — architecture described, source not public",
    "project.evidence": "evidence",
    "project.role.solo": "Solo",
    "project.role.lead": "Lead",
    "project.role.contributor": "Contributor",
    "metrics.commits": "commits",
    "metrics.activeDays": "active days",
    "metrics.span": "span",
    "metrics.languages": "Languages",
    "metrics.activity": "Commit Activity",
    "metrics.velocity": "commits/active day",
    "metrics.byOwner": "own commits",
    "metrics.days": "d",
    "metrics.prs": "PRs",
    "metrics.conventional": "conventional commits",
    "viz.less": "less",
    "viz.more": "more",
    "viz.weeks": "weeks",
    "category.product": "Product",
    "category.service": "Service",
    "category.client": "Client",
    "category.oss": "OSS",
    "category.hobby": "Hobby",
    "category.learning": "Learning",
    "evidence.owner": "owner",
    "history.title": "Development History",
    "history.empty": "As projects accumulate, a cross-project timeline grows here.",
    "about.title": "About",
    "about.skills": "Skills (computed from all projects, evidence-linked)",
    "overview.title": "Overview",
    "overview.note": "The one-page summary.",
    "seo.defaultTitle": "Developer Portfolio",
    "footer.builtWith": "Generated by Provenfolio",
    "theme.switcher": "Design",
  },
};

export function ui(key: string, locale: string): string {
  return UI[locale]?.[key] ?? UI.en?.[key] ?? key;
}

/** Native (endonym) display name of a locale, e.g. "ja" → "日本語". */
export function languageLabel(locale: string): string {
  try {
    const name = new Intl.DisplayNames([locale], { type: "language" }).of(locale);
    return name ? name.charAt(0).toUpperCase() + name.slice(1) : locale.toUpperCase();
  } catch {
    return locale.toUpperCase();
  }
}
