/**
 * New-owner reset — used by /setup. Wipes the previous owner's instance data
 * and writes a blank-slate profile the interview then fills in.
 *
 * Usage: tsx engine/scripts/reset-data.ts --confirm
 * (The flag is mandatory: this deletes data/. /setup passes it after the
 * user explicitly agrees.)
 */
import fs from "node:fs";
import path from "node:path";
import { SCHEMA_VERSION } from "../schemas/index.js";
import {
  DATA_DIR,
  PROJECTS_DIR,
  INTAKE_DIR,
  ACTIVITIES_DIR,
  DERIVED_DIR,
  ASSETS_DIR,
  PROFILE_FILE,
  MANIFEST_FILE,
  AGGREGATES_FILE,
  WORKSPACE_DIR,
  ROOT,
} from "./lib/paths.js";
import { writeJson, readJson } from "./lib/io.js";

if (!process.argv.includes("--confirm")) {
  console.error(
    "reset-data deletes everything in data/ (projects, intake, assets, profile).\n" +
      "Run with --confirm only after the owner explicitly agreed (normally via /setup)."
  );
  process.exit(2);
}

const engineVersion = (readJson(path.join(ROOT, "package.json")) as { version: string })
  .version;
const now = new Date().toISOString();

for (const dir of [PROJECTS_DIR, INTAKE_DIR, ACTIVITIES_DIR, DERIVED_DIR, ASSETS_DIR]) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
}
fs.rmSync(WORKSPACE_DIR, { recursive: true, force: true });
fs.mkdirSync(path.join(ASSETS_DIR, "screenshots"), { recursive: true });

writeJson(PROFILE_FILE, {
  schemaVersion: SCHEMA_VERSION,
  name: "Your Name",
  githubUser: "your-github-username",
  role: { en: "Software Developer" },
  tagline: { en: "From idea to working product." },
  bio: { en: "Tell your story here (or let /setup do it)." },
  socials: [],
  sourceLang: "en",
  targetLangs: [],
  identities: [],
  seo: {
    title: "Developer Portfolio",
    description: { en: "Portfolio generated by Provenfolio." },
  },
  skillOverrides: [],
  updatedAt: now,
});

writeJson(MANIFEST_FILE, {
  schemaVersion: SCHEMA_VERSION,
  engineVersion,
  lastUpdated: now,
  projects: [],
});

writeJson(AGGREGATES_FILE, {
  schemaVersion: SCHEMA_VERSION,
  generatedAt: now,
  totals: { projects: 0, commits: 0, activeDays: 0 },
  techFrequency: [],
  projectSpans: [],
  yearlyActivity: [],
});

console.log(
  `✓ data/ reset for a new owner (engine ${engineVersion}) — run /setup to fill the profile, then /analyze your first repo`
);
