/**
 * Blank-slate seed for data/ — shared by reset-data (destructive, --confirm)
 * and ensure-data (non-destructive bootstrap on a data-less clone).
 * The distribution repo tracks no data/ paths; this module is the single
 * source of truth for what a fresh instance starts from.
 */
import fs from "node:fs";
import path from "node:path";
import { SCHEMA_VERSION } from "../../schemas/index.js";
import {
  PROJECTS_DIR,
  INTAKE_DIR,
  ACTIVITIES_DIR,
  DERIVED_DIR,
  ASSETS_DIR,
  PROFILE_FILE,
  MANIFEST_FILE,
  AGGREGATES_FILE,
  ROOT,
} from "./paths.js";
import { writeJson, readJson } from "./io.js";

/** Create the data/ directory tree (idempotent, never deletes). */
export function ensureDataDirs(): void {
  for (const dir of [PROJECTS_DIR, INTAKE_DIR, ACTIVITIES_DIR, DERIVED_DIR, ASSETS_DIR]) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.mkdirSync(path.join(ASSETS_DIR, "screenshots"), { recursive: true });
}

/**
 * Write the blank seed files. With overwrite=false, existing files are left
 * untouched (safe on a live instance). Returns repo-relative paths written.
 */
export function writeSeedFiles(opts: { overwrite: boolean }): string[] {
  const engineVersion = (readJson(path.join(ROOT, "package.json")) as { version: string })
    .version;
  const now = new Date().toISOString();
  const written: string[] = [];

  const seeds: Array<[string, unknown]> = [
    [
      PROFILE_FILE,
      {
        schemaVersion: SCHEMA_VERSION,
        name: "Your Name",
        githubUser: "your-github-username",
        role: { en: "Software Developer" },
        tagline: { en: "From idea to working product." },
        bio: { en: "Tell your story here (or let /setup do it)." },
        socials: [],
        sourceLang: "en",
        targetLangs: [],
        identities: [],
        seo: {
          title: { en: "Developer Portfolio" },
          description: { en: "Portfolio generated by Provenfolio." },
        },
        skillOverrides: [],
        updatedAt: now,
      },
    ],
    [
      MANIFEST_FILE,
      {
        schemaVersion: SCHEMA_VERSION,
        engineVersion,
        lastUpdated: now,
        projects: [],
      },
    ],
    [
      AGGREGATES_FILE,
      {
        schemaVersion: SCHEMA_VERSION,
        generatedAt: now,
        totals: { projects: 0, commits: 0, activeDays: 0 },
        techFrequency: [],
        projectSpans: [],
        yearlyActivity: [],
      },
    ],
  ];

  for (const [file, value] of seeds) {
    if (!opts.overwrite && fs.existsSync(file)) continue;
    writeJson(file, value);
    written.push(path.relative(ROOT, file));
  }
  return written;
}
